### ISSUE TITLE
Documentation a little confusing ;)

### ISSUE THREAD

**Issue by vincegre** [bhuebschen/circle-menu-card#1]
Hi

Card can only be added in manual mode by editing yaml of lovelace right ? as it doesn't show up in list of Lovelace cards in my system even if installation went all good.

Thanks

Vincèn

**Comment by bhuebschen** [comment]
Hey Vincèn,

i've added the code to make it discoverable in the card-list :-)

**Comment by vincegre** [comment]
Thanks @bhuebschen :)

**Comment by vincegre** [comment]
I have updated the repo in HACS, it has downloaded version 1.01, restarted HA that is in latest version but still it doesn't show up in custom cards in Lovelace  :(

**Comment by bhuebschen** [comment]
> I have updated the repo in HACS, it has downloaded version 1.01, restarted HA that is in latest version but still it doesn't show up in custom cards in Lovelace :(

Sorry for the question.. but did you try to clear your (browser)cache?

**Comment by vincegre** [comment]
> > I have updated the repo in HACS, it has downloaded version 1.01, restarted HA that is in latest version but still it doesn't show up in custom cards in Lovelace :(
> 
> Sorry for the question.. but did you try to clear your (browser)cache?

Yeah I did but it was an other problem with browser but all good now, thanks for support :)
