### ISSUE TITLE
Can a call service be executed when the menu button is tapped?

### ISSUE THREAD

**Issue by kkqq9320** [bhuebschen/circle-menu-card#5]
Hello. First of all, thank you for your excellent work.

I need to return to the main dashboard screen using navigate_path rather than having many menus. Instead of opening a menu when tapping, is it possible to execute a call-service action?

Or, I would appreciate it if a double-tap action or hold action could be added.

Thank you again.

**Comment by bhuebschen** [comment]
Hi :) 

After careful consideration of the feature request, I have decided to create a new component dedicated to the purpose of handling navigation and service calls via a single button. This decision is based on the need to maintain a clear separation of concerns and to ensure that each component remains focused on its primary function.

**Comment by bhuebschen** [comment]
Please take a look at https://github.com/bhuebschen/fab-card

**Comment by kkqq9320** [comment]
You're really amazing. Thank you so much!
I'll make good use of it.
